const env = {
    FIREBASE_API_KEY: 'YOUR_API_KEY',
    FIREBASE_AUTH_DOMAIN: 'YOUR_AUTH_DOMAIN',
    FIREBASE_PROJECT_ID: 'YOUR_PROJECT_ID',
    FIREBASE_STORAGE_BUCKET: 'YOUR_STORAGE_BUCKET',
    POWERBI_EMBED_URL: 'YOUR_EMBED_URL',
  };
  
  export default env;